### PR TITLE
Add octet stream header for download trust store cert

### PR DESCRIPTION
**Pull request by Anisha2510**
## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type  

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

## What is the current behavior?  
The header content type was not set to download trust store cert, as the content type octet-stream was not being accepted in the API call. Only json was being accepted.

## What is the new behavior?  
The header content type has now been set to download only trust store cert of type octet-stream.

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Anisha2510** [comment]
Testing

Tested in sdk to call DownloadTrustStoreCertificate

Tested with header `builder.AddHeader("Accept", "application/json")` --> Got err as not acceptable
Screenshot 2024-03-28 at 12 03 58

Tested with header `builder.AddHeader("Accept", "application/octet-stream")` --> Can download cert successfully 
Screenshot 2024-03-28 at 12 12 00


Tested using curl commands

Tested with header `builder.AddHeader("Accept", "application/json")` --> Got err as not acceptable

Tested with header `builder.AddHeader("Accept", "application/octet-stream")` --> Can download cert successfully

**Comment by Anisha2510** [comment]
Not implemented in terraform as downloading of cert API call is not implemented in terraform currently.

**Comment by shuaibabubakker** [comment]
PR looks good to me

See https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format

And its a `fix` type right? `pat` is not here

**Review by shuaibabubakker — APPROVED** [review]
LGTM

**Comment by Anisha2510** [comment]
I have kept the commit as refactor since it does not have any functional or api changes

**Pull request merged**
